"""
graphics_os -- an example OS with a real boot animation, a background
image, and a home-screen logo, using VGA Mode 13h (320x200, 256-color).

Boot flow:
  1. Loading screen: plays a short progress-bar animation (a real "video"
     -- a sequence of frames shown in order with a delay between them).
  2. Home screen: a full-screen background image with a logo composited
     on top (two separate images, blitted to different screen regions).
  3. Halts, leaving the home screen displayed.

Uses placeholder art generated by examples/assets/generate_assets.py --
run that first (or just run this script, which does it for you if the
assets are missing). Swap in your own PNGs any time; aetherix.imaging
handles resizing and color quantization for whatever you give it.

Run:
    python examples/graphics_os.py

Then boot the produced image in an emulator, e.g.:
    qemu-system-i386 -drive file=graphics_os.img,format=raw

Or verify it under CPU emulation without needing QEMU installed:
    pip install unicorn
    python tests/emulate.py build/graphics_os.img
(the emulator prints the VGA text buffer, which will be blank here since
this example only uses graphics mode -- see tests/test_emulation.py for
how the framebuffer/palette are checked instead.)
"""
import sys
import subprocess
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from aetherix import Project, imaging
from aetherix.drivers import graphics

ASSETS_DIR = Path(__file__).resolve().parent / "assets"

if not (ASSETS_DIR / "background.png").exists():
    print("Generating placeholder assets...")
    subprocess.run([sys.executable, str(ASSETS_DIR / "generate_assets.py")], check=True)

# -- Prepare assets at build time (resizing/quantizing happens here, not
#    at boot -- the kernel only ever handles already-prepared bytes) --
loading_frames = [
    imaging.load_image(ASSETS_DIR / f"loading_{i}.png") for i in range(6)
]

# background and logo will be on screen AT THE SAME TIME, so they must
# share one 256-color palette -- VGA Mode 13h has a single palette for the
# whole screen, not one per image (see imaging.load_images_shared_palette).
background, logo = imaging.load_images_shared_palette([
    (ASSETS_DIR / "background.png", graphics.GFX_WIDTH, graphics.GFX_HEIGHT, True),
    (ASSETS_DIR / "logo.png", 64, 64, False),
])

LOGO_X = (graphics.GFX_WIDTH - logo.width) // 2
LOGO_Y = (graphics.GFX_HEIGHT - logo.height) // 2

with Project("GraphicsOS", graphics_mode=graphics.MODE_13H) as os_:

    @os_.kernel_entry
    def main(prog, drivers):
        # 1. Loading animation -- plays once, then falls through.
        drivers.graphics.play_frames(prog, loading_frames, delay_iterations=3_000_000, loop=False)

        # 2. Home screen -- background, then a logo composited on top.
        drivers.graphics.show_image(prog, background, x=0, y=0)
        drivers.graphics.show_image(prog, logo, x=LOGO_X, y=LOGO_Y)

        prog.hlt()

    out_dir = Path(__file__).resolve().parent.parent / "build"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = os_.build(str(out_dir / "graphics_os.img"))
    print(f"Built: {out} ({out.stat().st_size} bytes)")
    print(f"Kernel sectors: {(len(os_.kernel.assemble()) + 511) // 512}")
    print("Boot it with: qemu-system-i386 -drive file=graphics_os.img,format=raw")
